name: BuildExe
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.7"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        working-directory: ${{  GITHUB_ACTION_PATH }}
        run: poetry install

      - name: Bundle
        run: poetry run make bundle_windows
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: Buzz-${{ runner.os }}
          path: |
            dist/Buzz*-windows.exe
      